agger: "2.0"
info:
  title: Cloud Source Repositories
  description: Access source code repositories hosted by Google.
  contact:
    name: Google
    url: https://google.com
  version: v1
host: sourcerepo.googleapis.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /v1/{name}:
    delete:
      summary: Delete Repo
      description: Deletes a repo
      operationId: sourcerepo.projects.repos.delete
      parameters:
      - in: path
        name: name
        description: The name of the repo to delete
      responses:
        200:
          description: OK
      tags:
      - Repository
    get:
      summary: Get Repo
      description: Returns information about a repo
      operationId: sourcerepo.projects.repos.get
      parameters:
      - in: path
        name: name
        description: The name of the requested repository
      responses:
        200:
          description: OK
      tags:
      - Repository
  /v1/{name}/repos:
    get:
      summary: Get Repos
      description: Returns all repos belonging to a project
      operationId: sourcerepo.projects.repos.list
      parameters:
      - in: path
        name: name
        description: The project ID whose repos should be listed
      responses:
        200:
          description: OK
      tags:
      - Repository
  /v1/{parent}/repos:
    post:
      summary: Create Repo
      description: Creates a repo in the given project with the given name
      operationId: sourcerepo.projects.repos.create
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: parent
        description: The project in which to create the repo
      responses:
        200:
          description: OK
      tags:
      - Repository
  /v1/{resource}:getIamPolicy:
    get:
      summary: Get Access Control Policy
      description: Gets the access control policy for a resource
      operationId: sourcerepo.projects.repos.getIamPolicy
      parameters:
      - in: path
        name: resource
        description: 'REQUIRED: The resource for which the policy is being requested'
      responses:
        200:
          description: OK
      tags:
      - Repository Policy
  /v1/{resource}:setIamPolicy:
    post:
      summary: Set Access Control Policy
      description: Sets the access control policy on the specified resource
      operationId: sourcerepo.projects.repos.setIamPolicy
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: resource
        description: 'REQUIRED: The resource for which the policy is being specified'
      responses:
        200:
          description: OK
      tags:
      - Repository Policy
  /v1/{resource}:testIamPermissions:
    post:
      summary: Return Permissions
      description: Returns permissions that a caller has on the specified resource
      operationId: sourcerepo.projects.repos.testIamPermissions
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/holder'
      - in: path
        name: resource
        description: 'REQUIRED: The resource for which the policy detail is being
          requested'
      responses:
        200:
          description: OK
      tags:
      - Repository Policy
definitions:
  AuditConfig:
    properties:
      auditLogConfigs:
        description: This is a default description.
        type: post
      exemptedMembers:
        description: This is a default description.
        type: post
      service:
        description: This is a default description.
        type: post
  AuditLogConfig:
    properties:
      exemptedMembers:
        description: This is a default description.
        type: post
      logType:
        description: This is a default description.
        type: post
  Binding:
    properties:
      members:
        description: This is a default description.
        type: post
      role:
        description: This is a default description.
        type: post
  CloudAuditOptions:
    properties: []
  Condition:
    properties:
      iam:
        description: This is a default description.
        type: post
      op:
        description: This is a default description.
        type: post
      svc:
        description: This is a default description.
        type: post
      sys:
        description: This is a default description.
        type: post
      value:
        description: This is a default description.
        type: post
      values:
        description: This is a default description.
        type: post
  CounterOptions:
    properties:
      field:
        description: This is a default description.
        type: post
      metric:
        description: This is a default description.
        type: post
  DataAccessOptions:
    properties: []
  Empty:
    properties: []
  ListReposResponse:
    properties:
      repos:
        description: This is a default description.
        type: post
  LogConfig:
    properties: []
  MirrorConfig:
    properties:
      deployKeyId:
        description: This is a default description.
        type: post
      url:
        description: This is a default description.
        type: post
      webhookId:
        description: This is a default description.
        type: post
  Policy:
    properties:
      auditConfigs:
        description: This is a default description.
        type: post
      bindings:
        description: This is a default description.
        type: post
      etag:
        description: This is a default description.
        type: post
      iamOwned:
        description: This is a default description.
        type: post
      rules:
        description: This is a default description.
        type: post
      version:
        description: This is a default description.
        type: post
  Repo:
    properties:
      name:
        description: This is a default description.
        type: post
      size:
        description: This is a default description.
        type: post
      url:
        description: This is a default description.
        type: post
  Rule:
    properties:
      action:
        description: This is a default description.
        type: post
      conditions:
        description: This is a default description.
        type: post
      description:
        description: This is a default description.
        type: post
      in:
        description: This is a default description.
        type: post
      logConfig:
        description: This is a default description.
        type: post
      notIn:
        description: This is a default description.
        type: post
      permissions:
        description: This is a default description.
        type: post
  SetIamPolicyRequest:
    properties:
      updateMask:
        description: This is a default description.
        type: post
  TestIamPermissionsRequest:
    properties:
      permissions:
        description: This is a default description.
        type: post
  TestIamPermissionsResponse:
    properties:
      permissions:
        description: This is a default description.
        type: post