swagger: "2.0"
info:
  title: Google Cloud Functions
  description: API for managing lightweight user-provided functions executed in response
    to events.
  contact:
    name: Google
    url: https://google.com
  version: v1
host: cloudfunctions.googleapis.com
basePath: /
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  /v1/{name}:
    get:
      summary: Get Location
      description: Get information about a location
      operationId: cloudfunctions.projects.locations.get
      parameters:
      - in: path
        name: name
        description: Resource name for the location
      responses:
        200:
          description: OK
      tags:
      - Location
definitions:
  Location:
    properties:
      labels:
        description: This is a default description.
        type: parameters
      locationId:
        description: This is a default description.
        type: parameters
      metadata:
        description: This is a default description.
        type: parameters
      name:
        description: This is a default description.
        type: parameters
  OperationMetadataV1Beta2:
    properties:
      request:
        description: This is a default description.
        type: parameters
      target:
        description: This is a default description.
        type: parameters
      type:
        description: This is a default description.
        type: parameters